apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-monitor-app
  namespace: monitoring
  labels:
    app: flask-monitor-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-monitor-app
  template:
    metadata:
      labels:
        app: flask-monitor-app
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: flask-monitor-app
        image: kluivertanyang/flask-monitor-app:v1.0
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
